name: Deploy Portfolio1 to Main Repo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: Node 설치
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 설치
        run: npm install

      - name: 빌드
        run: npm run build

      - name: 메인 레포 clone
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/iamyuna/iamyuna.github.io.git

      - name: dist 복사
        run: |
          rm -rf iamyuna.github.io/2026_portfolio
          mkdir iamyuna.github.io/2026_portfolio
          cp -r dist/* iamyuna.github.io/2026_portfolio/

      - name: push
        run: |
          cd iamyuna.github.io
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "deploy 2026_portfolio"
          git push