name: Deploy to iamyuna.github.io/2026_portfolio

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to main repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git clone https://x-access-token:$GH_TOKEN@github.com/iamyuna/iamyuna.github.io.git
          
          rm -rf iamyuna.github.io/2026_portfolio
          mkdir iamyuna.github.io/2026_portfolio
          
          cp -r dist/* iamyuna.github.io/2026_portfolio/

          cd iamyuna.github.io
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "deploy: 2026_portfolio"
          git push